### ISSUE TITLE
Change German Translation "Zeitabrechnung" to "Zeiterfassung"

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/TimeAccounting#1]
Hi,

for me the word "Zeiterfassung" fits better, any other opinions?

Thanks,

Stefan

**Comment by bschmalhofer** [comment]
Yes, I think Zeiterfassung ist the commonly used word.

**Comment by MarkusHlinka-OTOBO** [comment]
German translation for strings with "Zeiterfassung" changed to "Zeitabrechnung" + finalize German translation - see ccd200e.
